---
services:
  db:
    image: ujjvalpedaprolu/2nd-project:db_image
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
  auth_service:
    image: ujjvalpedaprolu/2nd-project:auth_image  
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    depends_on:
      - db
  book_service:
    image: ujjvalpedaprolu/2nd-project:book_image
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    depends_on:
      - db
  borrow_service:
    image: ujjvalpedaprolu/2nd-project:borrow_image
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    depends_on:
      - db
  frontend_service:
    image: ujjvalpedaprolu/2nd-project:frontend
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    depends_on:
      - auth_service
      - book_service
      - borrow_service

networks:
  mynetwork:
    driver: overlay
